# Generated by Django 5.1.1 on 2024-09-06 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='room_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='username',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.room'),
            preserve_default=False,
        ),
    ]
